
<!doctype html>
<html lang="en">
<?php include __DIR__ . '/partials/head.phtml' ?>

<body class="bg-light">

<div class="container">
    <div class="py-5 text-center">
        <h1>Pragmatic Event Sourcing</h1>
        <h2>Confirmation</h2>
    </div>

    <div class="row">
        <?= $cartItemList ?>
        <div class="col-md-8 order-md-1">
            <h4 class="mb-3">Billing address</h4>
            <?= $billingAddress ?>
        </div>
</div>

    <form action="/placeOrder" method="POST">
        <button class="btn btn-primary btn-lg btn-block" type="submit">Submit</button>
    </form>

    <?php include __DIR__ . '/partials/footer.phtml' ?>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="../../assets/js/vendor/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="../../assets/js/vendor/holder.min.js"></script>
</body>
</html>
